/*
* This Java source file was generated by the Gradle 'init' task.
*/

package assignmenttwo;

/**
* This is the generated Hello World Greeting App.
*/
public class App {
  
  private void sunPlanetMoon() {

    assignmenttwo.solitares.Star sun = new assignmenttwo.solitares.Star("Sun", 6304761);
    System.out.println("Solar System:");
    System.out.println();
    System.out.println(sun.toString());
    System.out.println();
    
    assignmenttwo.solitares.Planet[] planets = new assignmenttwo.solitares.Planet[4];
    
    assignmenttwo.solitares.Planet mercury = new assignmenttwo.solitares.Planet("Mercury", 2439);
    planets[0] = mercury;
    assignmenttwo.solitares.Planet venus = new assignmenttwo.solitares.Planet("Venus", 6051);
    planets[1] = venus;
    assignmenttwo.solitares.Planet earth = new assignmenttwo.solitares.Planet("Earth", 6371);
    planets[2] = earth;
    assignmenttwo.solitares.Planet mars = new assignmenttwo.solitares.Planet("Mars", 3389);
    planets[3] = mars;
    
    assignmenttwo.solitares.Moon[] moons = new assignmenttwo.solitares.Moon[4];
    
    assignmenttwo.solitares.Moon moon = new assignmenttwo.solitares.Moon("Moon", 1737);
    moons[0] = moon;
    assignmenttwo.solitares.Moon phobos = new assignmenttwo.solitares.Moon("Phobos", 12);
    moons[1] = phobos;
    assignmenttwo.solitares.Moon io = new assignmenttwo.solitares.Moon("Io", 1821);
    moons[2] = io;
    assignmenttwo.solitares.Moon europa = new assignmenttwo.solitares.Moon("Europa", 1560);
    moons[3] = europa;
    
    System.out.println("Planets: ");
    
    for (int i = 0; i < 4; i++) {
      System.out.println(planets[i]);
    }
    System.out.println();
    System.out.println("Moons: ");
    
    for (int i = 0; i < 4; i++) {
      System.out.println(moons[i]);
    }

  }
  
  
  private void heavenlyBody() {
    assignmenttwo.refactoredsolitares.Star sun = new assignmenttwo.refactoredsolitares.Star("Sun", 6304761);
    System.out.println("Solar System:");
    System.out.println();
    System.out.println(sun.toString());
    System.out.println();

    assignmenttwo.refactoredsolitares.Planet[] planets = new assignmenttwo.refactoredsolitares.Planet[4];

    assignmenttwo.refactoredsolitares.Planet mercury = new assignmenttwo.refactoredsolitares.Planet("Mercury", 2439);
    planets[0] = mercury;
    assignmenttwo.refactoredsolitares.Planet earth = new assignmenttwo.refactoredsolitares.Planet("Earth", 6371);
    planets[1] = earth;
    assignmenttwo.refactoredsolitares.Planet venus = new assignmenttwo.refactoredsolitares.Planet("Venus", 6051);
    planets[2] = venus;
    assignmenttwo.refactoredsolitares.Planet mars = new assignmenttwo.refactoredsolitares.Planet("Mars", 3389);
    planets[3] = mars;

    assignmenttwo.refactoredsolitares.Moon[] moons = new assignmenttwo.refactoredsolitares.Moon[4];

    assignmenttwo.refactoredsolitares.Moon moon = new assignmenttwo.refactoredsolitares.Moon("Moon", 1737);
    moons[0] = moon;
    assignmenttwo.refactoredsolitares.Moon phobos = new assignmenttwo.refactoredsolitares.Moon("Phobos", 12);
    moons[1] = phobos;
    assignmenttwo.refactoredsolitares.Moon io = new assignmenttwo.refactoredsolitares.Moon("Io", 1821);
    moons[2] = io;
    assignmenttwo.refactoredsolitares.Moon europa = new assignmenttwo.refactoredsolitares.Moon("Europa", 1560);
    moons[3] = europa;

    System.out.println("Planets: ");
    
    for (int i = 0; i < 4; i++) {
      System.out.println(planets[i]);
    }
    System.out.println();
    System.out.println("Moons: ");
    
    for (int i = 0; i < 4; i++) {
      System.out.println(moons[i]);
    }

  }
  
  private void solarSytem() {
    assignmenttwo.solarsystem.Star star = new assignmenttwo.solarsystem.Star("Sun", 696342, 201);
    assignmenttwo.solarsystem.Planet earthPlanet = star.addPlanet("earth", 6371, 6371000);
    earthPlanet.addMoon("Moon", 1737, 1737000);

    assignmenttwo.solarsystem.Planet marsPlanet = star.addPlanet("Mars", 3389, 3389000);
    marsPlanet.addMoon("phobos", 12, 12000);
    marsPlanet.addMoon("deimos", 6, 6000);


    assignmenttwo.solarsystem.Planet jupiterPlanet = star.addPlanet("Jupiter", 69911, 6911000);
    jupiterPlanet.addMoon("io", 1821, 1821000);
    jupiterPlanet.addMoon("europa", 1560, 1560000);
    jupiterPlanet.addMoon("ganymede", 2634, 2634000);
    jupiterPlanet.addMoon("callisto", 2410, 2410000);

    assignmenttwo.solarsystem.Planet saturnPlanet = star.addPlanet("saturn", 58232, 58232000);
    saturnPlanet.addMoon("mimas", 198, 198000);
    saturnPlanet.addMoon("enceladus", 252, 252000);
    saturnPlanet.addMoon("tethys", 533, 533000);
    saturnPlanet.addMoon("dione", 561, 561000);
    saturnPlanet.addMoon("rhea", 764, 764000);
    saturnPlanet.addMoon("titan", 2575, 2575000);
    System.out.println(star.toString());
  }
  
  
  /**
  * The App starting point.
  *
  * @param args Unused program arguments.
  */
  public static void main(String[] args) {
    App theApp = new App();
    theApp.sunPlanetMoon();
    theApp.heavenlyBody();
    theApp.solarSytem();
  }
}
